CONFIG_FILE = "./epr-config.json"

EDITOR_LIST_KEY = "editor-list"
SAVE_SELECTION_CHECKBOX_KEY = "save-selection-checkbox"
OPEN_CONFIG_KEY = "config-button"
SUBMIT_KEY = "submit-button"

CONFIG_EDITOR_LIST_KEY = ""
CONFIG_EDITOR_REMOVE_KEY = ""
CONFIG_EDITOR_ADD_KEY = ""
CONFIG_EDITOR_DETECT_KEY = ""
CONFIG_EDITOR_RENAME_KEY = ""

CONFIG_EDITOR_REMOVE_ASSOCIATIONS_KEY = ""
CONFIG_SAVE_KEY = "config-save-button"

EXIT_ICON_KEY = "exit-icon"